name: testlab
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.16.0+1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/1_background.jpg
   - assets/1_drop_down_arrow.png
   - assets/2_background.jpg
   - assets/2_KPSS.png
   - assets/2_TYT.png
   - assets/2_AYT.png
   - assets/Lessons/Kimya.png
   - assets/Lessons/Matematik.png
   - assets/Lessons/Turkce.png
   - assets/Lessons/Geometri.png
   - assets/Lessons/Vatandaslik.png
   - assets/Lessons/Cografya.png
   - assets/Lessons/Tarih.png
   - assets/Lessons/Guncel_Bilgiler.png
   - assets/Lessons/Turk_Dili_Edebiyati.png
   - assets/Lessons/Fizik.png
   - assets/Lessons/Biyoloji.png
   - assets/Lessons/Felsefe.png
   - assets/Lessons/Din.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ceaswfte
      fonts:
        - asset: fonts/ceaswfte.ttf
    - family: cebswfte
      fonts:
        - asset: fonts/cebswfte.ttf
    - family: ceiswfte
      fonts:
        - asset: fonts/ceiswfte.ttf
    - family: Century Bold Italic
      fonts:
        - asset: fonts/Century Bold Italic.ttf
    - family: Century Bold
      fonts:
        - asset: fonts/Century Bold.ttf
    - family: Century Normal
      fonts:
        - asset: fonts/Century Normal.ttf
    - family: Century
      fonts:
        - asset: fonts/CENTURY.ttf
  #       style: Normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
